### ISSUE TITLE
`Submit` button behavior while adding new option to my voting

### ISSUE THREAD

**Issue by Sysa** [Beaglefoot/fcc-voting-app#2]
If i'll be add new option in my voting, but instead of pushing `enter` i'll click on submit - there will be new one vote result as `undefined: 1` on the chart.
better to hide/disable this submit button, or, add already new opinion to the chart (but it can be misunderstanding of UI)

**Comment by Beaglefoot** [comment]
This is fixed, thanks for letting me know!
